# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    handle_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_to_shoulder_attachment
      - shoulder_motor_to_shoulder_arm
      - shoulder_to_elbow
      - elbow_to_wrist_attachment
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
handle_controller:
  ros__parameters:
    joint: wrist_to_utensil
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity